### ISSUE TITLE
接続成功/失敗の表示はどうするべきか

### ISSUE THREAD

**Issue by kassy-kz** [eaglesakura/andriders-central-engine-v3#99]
Ant+デバイスにもBLEと同じくセッション開始時にコネクションを張るが
それの成功/失敗をどう表示するか。
ACE準拠で同じようなダイアログを出すなら、それを呼び出す口が欲しい。
（まぁプラグイン毎に独自に出しても良いが）

**Comment by eaglesakura** [comment]
* ACE組み込みの表示であれば、SDKを経由して通知用のカードを出す機能がある
  * この通知は放っておくと消える。Toastと同様。
 * 通常のダイアログ表示の機能を実装する予定はない（走行中はボタン押せないし）
 * SDK提供以外の手段で通知を出したい場合はPlugin側で適宜出すことを想定してる

![device-2016-08-03-233812](https://cloud.githubusercontent.com/assets/902427/17369515/9f03e3f0-59d3-11e6-97f8-94014144d9ea.png)
